export default [
    {
        id:1,
        name:'programming',
        icon:'/programming.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/Health.png',
        promp:''
    },
    {
        id:3,
        name:'creative',
        icon:'/creative.png',
        promp:''
    },
]